type Account {
    email: String! @unique
    user: User
}

type User {
    projects: [Project] @relation(name: "project_member")
    managedProjects: [Project] @relation(name: "project_manager")
    tasks: [Task] @relation
    handle: String @unique
    account: Account
}

type Project {
    tasks: [Task] @relation
    manager: User! @relation(name: "project_manager")
    members: [User] @relation(name: "project_member")
    title: String
}

type Invite {
    project: Project
    to: User! @relation(name: "invite_recipient")
    from: User! @relation(name: "invite_sender")
    accepted: Boolean
}

enum TaskStatus {
    done
    todo
    doing
}

type Task {
    status: TaskStatus
    project: Project
    title: String
    assignedTo: [User] @relation
}

type Query {
    allProjects: [Project]
    allUsers: [User]
}